#!/bin/sh

set -e
set -o pipefail
cd /lambda
if [ `lambda invoke | md5sum | cut -d ' ' -f 1` != '53fb4322cc3fe840f02530054ef93603' ]; then
  echo 'ERROR: md5sum of output returned by lambda invoke did not match expected results' 1&>2
  exit 1
fi

